[package]
name = "async_await"
version = "0.1.0"
authors = ["jaymzee <jaymzee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
async-std = "1.5.0"
